# Generated by Django 2.2.9 on 2020-12-09 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('birth', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='escola_v1.BaseUser')),
            ],
            bases=('escola_v1.baseuser',),
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='escola_v1.BaseUser')),
            ],
            bases=('escola_v1.baseuser',),
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('school_year', models.CharField(choices=[('1º PS', '1º ano primário'), ('2º PS', '2º ano primário'), ('1º BS', '1º ano fundamental'), ('2º BS', '2º ano fundamental'), ('3º BS', '3º ano fundamental'), ('4º BS', '4º ano fundamental'), ('5º BS', '5º ano fundamental'), ('6º BS', '6º ano fundamental'), ('7º BS', '7º ano fundamental'), ('8º BS', '8º ano fundamental'), ('9º BS', '9º ano fundamental'), ('1º HS', '1º ano medio'), ('2º HS', '2º ano medio'), ('3º HS', '3º ano medio')], max_length=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ManyToManyField(related_name='classes', to='escola_v1.Subjects')),
                ('student', models.ManyToManyField(related_name='classes', to='escola_v1.Students')),
                ('teachers', models.ManyToManyField(related_name='classes', to='escola_v1.Teachers')),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
            },
        ),
    ]
